### ISSUE TITLE
ApolloContextToken?

### ISSUE THREAD

**Issue by parkerdan** [fusionjs/fusion-plugin-apollo-server#28]
The Example:

```
import {ApolloContextToken} from 'fusion-apollo';

app.register(ApolloContextToken, ctx => {
  return {
    httpContext: ctx,
    otherContext: SOMEOHTERCONTEXT
  };
});
```

Outputs:

`TypeError: Cannot read property 'name' of undefined`

**Comment by parkerdan** [comment]
It's because of `fusion-apollo` version.  Need `"fusion-apollo": "^1.2.0-1",` or maybe `1-2-0-0`...but not compatible with `1.1.0`

**Comment by KevinGrandon** [comment]
We're going to publish a release soon which will update versions and peer versions. I think that the pre-release should be compatible, but please let us know if you're having any issues here.

**Comment by parkerdan** [comment]
What about some sort of body parser integration and graphiql?  Is that coming soon?

Both are things I want.  I have my own fusion-graphql implementation that works with a body parser for json posts requests, but I'd like to keep on this system.  Just missing those two features.

**Comment by parkerdan** [comment]
I'd also be happy to contribute and PR those features if it is not already in active dev...

**Comment by parkerdan** [comment]
I currently have `fusion-plugin-body-parser` and `fusion-plugin-apollo-server-graphiql` on my project.

I'll have to clean it up so its less opinionated and more extendable...we can chat later on this
