### ISSUE TITLE
Verify that mutations work and write test case

### ISSUE THREAD

**Issue by KevinGrandon** [fusionjs/fusion-plugin-apollo-server#53]
Currently we have a [test case for queries](https://github.com/fusionjs/fusion-plugin-apollo-server/blob/master/src/__tests__/server.node.js#L21), but no test case exists for mutations.

In https://github.com/KevinGrandon/fusion-boilerplate/issues/43 there was a report that mutations don't work with the local graphql server. It may be just missing the bodyParser middleware. We should look into fixing this, and adding a test so it doesn't regress in the future.

**Comment by ratson** [comment]
I am quite surprise this is not work of the box given the version is v1.1.2.
I would expect https://www.apollographql.com/docs/apollo-server/features/subscriptions.html won't work either. Is that Uber does not use this pattern internally? Should I expect full Apollo server integration is not officially supported?

**Comment by mlmorg** [comment]
This is done.
